(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(clojure-indent-style :always-indent)
 '(counsel-find-file-ignore-regexp nil)
 '(css-indent-offset 2)
 '(custom-safe-themes
   '("9be1d34d961a40d94ef94d0d08a364c3d27201f3c98c9d38e36f10588469ea57" default))
 '(eshell-output-filter-functions
   '(eshell-postoutput-scroll-to-bottom eshell-handle-control-codes eshell-handle-ansi-color))
 '(flycheck-display-errors-function 'flycheck-display-error-messages)
 '(flycheck-popup-tip-error-prefix "")
 '(git-gutter:window-width -1)
 '(global-hl-todo-mode t)
 '(hl-todo-keyword-faces
   '(("HOLD" . "#ffcb6b")
     ("TODO" . "#c792ea")
     ("NEXT" . "#ffcb6b")
     ("THEM" . "#ffcb6b")
     ("PROG" . "#ffcb6b")
     ("OKAY" . "#c3e88d")
     ("DONT" . "#f07178")
     ("FAIL" . "#f07178")
     ("DONE" . "#c3e88d")
     ("NOTE" . "#ffcb6b")
     ("KLUDGE" . "#f07178")
     ("HACK" . "#f07178")
     ("FIXME" . "#f07178")
     ("XXX" . "#f07178")
     ("XXXX" . "#f07178")))
 '(js2-strict-trailing-comma-warning nil)
 '(package-selected-packages
   '(polymode package-build shut-up epl git commander dash yascroll prodigy eshell-prompt-extras hl-todo rainbow-delimiters eval-sexp-fu f s evil-snipe evil-surround evil-nerd-commenter persp-projectile counsel-projectile swiper general evil-cleverparens spaceline telephone-line use-package powerline evil base16-theme))
 '(prettier-js-args '("prettier" "--single-quote" "--trailing-comma" "all"))
 '(prettier-js-command "npx")
 '(projectile-completion-system 'ivy)
 '(projectile-enable-caching nil)
 '(projectile-file-exists-local-cache-expire 30)
 '(projectile-globally-ignored-directories
   '(".idea" ".ensime_cache" ".eunit" ".git" ".hg" ".fslckout" "_FOSSIL_" ".bzr" "_darcs" ".tox" ".svn" ".stack-work" "node_modules"))
 '(python-indent-guess-indent-offset nil)
 '(tide-filter-out-warning-completions t)
 '(web-mode-code-indent-offset 2)
 '(web-mode-css-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(web-mode-sql-indent-offset 2))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 120 :family "Fira Code"))))
 '(clojure-keyword-face ((t (:inherit font-lock-keyword-face))))
 '(company-tooltip-common ((t (:inherit company-tooltip :weight bold :underline nil))))
 '(company-tooltip-common-selection ((t (:inherit company-tooltip-selection :weight bold :underline nil))))
 '(diff-hl-change ((t (:foreground "#ffcb6b"))))
 '(diff-hl-delete ((t (:foreground "#f07178"))))
 '(diff-hl-insert ((t (:foreground "#c3e88d"))))
 '(elixir-atom-face ((t (:inherit font-lock-constant-face))))
 '(elixir-attribute-face ((t (:inherit font-lock-keyword-face))))
 '(eshell-ls-archive ((t (:foreground "#c792ea"))))
 '(eshell-ls-backup ((t (:foreground "#ffcb6b"))))
 '(eshell-ls-clutter ((t (:foreground "#f78c6c"))))
 '(eshell-ls-directory ((t (:foreground "#89ddff"))))
 '(eshell-ls-executable ((t (:foreground "#c3e88d"))))
 '(eshell-ls-missing ((t (:foreground "#f07178"))))
 '(eshell-ls-product ((t (:foreground "#ffcb6b"))))
 '(eshell-ls-readonly ((t (:foreground "#b2ccd6"))))
 '(eshell-ls-special ((t (:foreground "#c792ea"))))
 '(eshell-ls-symlink ((t (:foreground "#89ddff"))))
 '(eshell-ls-unreadable ((t (:foreground "#353535"))))
 '(eshell-prompt ((t (:foreground "#c792ea" :weight bold))))
 '(eval-sexp-fu-flash ((t (:background "#82aaff" :foreground "#ffffff" :weight bold))))
 '(eval-sexp-fu-flash-error ((t (:foreground "#f07178" :weight bold))))
 '(flycheck-error-list-info ((t (:inherit success))))
 '(fringe ((t (:background "#212121"))))
 '(git-gutter:added ((t (:inherit default :foreground "#c3e88d" :weight bold))))
 '(git-gutter:deleted ((t (:inherit default :foreground "#f07178" :weight bold))))
 '(git-gutter:modified ((t (:inherit default :foreground "#ffcb6b" :weight bold))))
 '(js2-error ((t (:inherit font-lock-warning-face))))
 '(js2-external-variable ((t (:inherit font-lock-warning-face))))
 '(js2-function-param ((t (:inherit font-lock-variable-name-face))))
 '(js2-instance-member ((t (:inherit font-lock-function-name-face))))
 '(js2-jsdoc-html-tag-delimiter ((t (:inherit font-lock-negation-char-face))))
 '(js2-jsdoc-html-tag-name ((t (:inherit font-lock-keyword-face))))
 '(js2-jsdoc-tag ((t (:inherit font-lock-variable-name-face))))
 '(js2-jsdoc-type ((t (:inherit font-lock-constant-face))))
 '(js2-jsdoc-value ((t (:inherit font-lock-function-name-face))))
 '(js2-private-function-call ((t (:inherit font-lock-function-name-face))))
 '(js2-private-member ((t (:inherit font-lock-variable-name-face))))
 '(linum ((t (:foreground "#4a4a4a" :background "#212121"))))
 '(magit-bisect-bad ((t (:foreground "#f07178"))))
 '(magit-bisect-good ((t (:foreground "#c3e88d"))))
 '(magit-bisect-skip ((t (:foreground "#ff5370"))))
 '(magit-blame-heading ((t (:background "#353535" :foreground "#b2ccd6"))))
 '(magit-branch-local ((t (:foreground "#82aaff"))))
 '(magit-branch-remote ((t (:foreground "#c3e88d"))))
 '(magit-cherry-equivalent ((t (:foreground "#c792ea"))))
 '(magit-cherry-unmatched ((t (:foreground "#89ddff"))))
 '(magit-diff-added ((t (:foreground "#c3e88d"))))
 '(magit-diff-added-highlight ((t (:background "#353535" :foreground "#c3e88d"))))
 '(magit-diff-base ((t (:foreground "#ffcb6b"))))
 '(magit-diff-base-highlight ((t (:background "#353535" :foreground "#ffcb6b"))))
 '(magit-diff-lines-heading ((t (:inherit magit-diff-hunk-heading-highlight :background "#353535" :foreground "#ff5370"))))
 '(magit-diff-removed ((t (:foreground "#f07178"))))
 '(magit-diff-removed-highlight ((t (:background "#353535" :foreground "#f07178"))))
 '(magit-diffstat-added ((t (:foreground "#c3e88d"))))
 '(magit-diffstat-removed ((t (:foreground "#f07178"))))
 '(magit-dimmed ((t (:inherit font-lock-comment-face))))
 '(magit-hash ((t (:inherit font-lock-comment-face))))
 '(magit-log-author ((t (:foreground "#f07178"))))
 '(magit-log-date ((t (:inherit font-lock-comment-face))))
 '(magit-log-graph ((t (:inherit font-lock-comment-face))))
 '(magit-process-ng ((t (:inherit magit-section-heading :foreground "#f07178"))))
 '(magit-process-ok ((t (:inherit magit-section-heading :foreground "#c3e88d"))))
 '(magit-reflog-amend ((t (:foreground "#c792ea"))))
 '(magit-reflog-checkout ((t (:foreground "#82aaff"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#c3e88d"))))
 '(magit-reflog-commit ((t (:foreground "#c3e88d"))))
 '(magit-reflog-merge ((t (:foreground "#c3e88d"))))
 '(magit-reflog-other ((t (:foreground "#89ddff"))))
 '(magit-reflog-rebase ((t (:foreground "#c792ea"))))
 '(magit-reflog-remote ((t (:foreground "#89ddff"))))
 '(magit-reflog-reset ((t (:foreground "#f07178"))))
 '(magit-refname ((t (:inherit default))))
 '(magit-section-heading ((t (:foreground "#ffcb6b" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#ff5370"))))
 '(magit-section-highlight ((t (:background "#353535"))))
 '(magit-sequence-drop ((t (:foreground "#f07178"))))
 '(magit-sequence-head ((t (:foreground "#82aaff"))))
 '(magit-sequence-part ((t (:foreground "#ffcb6b"))))
 '(magit-sequence-stop ((t (:foreground "#c3e88d"))))
 '(magit-signature-bad ((t (:foreground "#f07178"))))
 '(magit-signature-good ((t (:foreground "#c3e88d"))))
 '(magit-signature-untrusted ((t (:foreground "#89ddff"))))
 '(magit-tag ((t (:foreground "#ffcb6b"))))
 '(prodigy-green-face ((t (:foreground "#c3e88d"))))
 '(prodigy-red-face ((t (:foreground "#f07178"))))
 '(prodigy-yellow-face ((t (:foreground "#ffcb6b"))))
 '(tide-hl-identifier-face ((t (:inherit highlight)))))
